spring:
  application:
    name: eureka-ha

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

#logbackConfigLocation: classpath:logback-prd.xml
logging.config: classpath:logback.xml
